// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ0oIj7Z9GsFAe9s5H92IQAJIfCE2tr0E',
    appId: '1:1023466396071:web:d1d8af6b2b2b391d1d3e82',
    messagingSenderId: '1023466396071',
    projectId: 'edu-vista-973d3',
    authDomain: 'edu-vista-973d3.firebaseapp.com',
    storageBucket: 'edu-vista-973d3.appspot.com',
    measurementId: 'G-FLRJTXDCJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-hbZ5q7Ro7ZEsZTJ_piYdfw0Z12si580',
    appId: '1:1023466396071:android:7d05e574622d7a181d3e82',
    messagingSenderId: '1023466396071',
    projectId: 'edu-vista-973d3',
    storageBucket: 'edu-vista-973d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAimCwGtfGODPxOIorUKL1lLz-oZE6t8EY',
    appId: '1:1023466396071:ios:28c5cab6cb6eb8d51d3e82',
    messagingSenderId: '1023466396071',
    projectId: 'edu-vista-973d3',
    storageBucket: 'edu-vista-973d3.appspot.com',
    iosBundleId: 'com.example.eduVista',
  );
}
